version: '3'
services:
  api:
    build: ./api
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
